### ISSUE TITLE
Update README and Archive Repository

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/oscal-cat#118]
Hi, I heard back from individuals today that are part or a group or the individual assigned to complete this work for this repo. I am going to provide some clarifying guidance on the different steps for this repo in this order:

- [x] Create a PR and add this section to the top of the README, using [the wording I am providing in this HackMD](https://hackmd.io/BDUgAm96QC6CrP_wQSuqig), get it reviewed, and merged as quickly as possible.
- [x] Add a banner to the application landing page. If you do not use the USWDS, you should still mimic the style of the example as seen in the example below. You are imitating the blue box in this screenshot. Replace "This website is in the alpha stage of development. Help us improve ->" with the following text for this project's website: "This website and its code are no longer under active development, read more details [here](https://github.com/usnistgov/oscal-cat#project-status)." You do not want to include help us improve: the link to the README page with the updated project status will suffice. Instead of the bright blue color, please set the background to `#d9e8f6`.

![Image](https://user-images.githubusercontent.com/94922603/225163904-2dea5a27-1868-4e19-a75a-38a34db1c51d.png)

- [x] Cut a final 0.2.0 release for this project and merge the code to main for a final deploy on oscal-tools site for cross-referenced issues elsewhere in this repo.
- [x] Archive the project [using the instructions from GitHub](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#archiving-a-repository). If you do not have sufficient permissions, please reach out to @aj-stein-nist to get this done.

**Comment by aj-stein-nist** [comment]
@JustKuzya, I know we discussed this in this office yesterday while in passing, but can you please work on this during the sprint? If you cannot complete this before 15 March 2023, please let me know.

**Comment by nikitawootten-nist** [comment]
Update: the team plans to draft a unified archiving message before making individual PRs.

**Comment by aj-stein-nist** [comment]
@JustKuzya and @nikitawootten-nist I heard from some the actionable steps to complete this were unclear, so I just added some copy and provided UI recommendations for the app to be merged before archiving the repo. Let me know if there is anything blocking you from getting this done.

https://github.com/usnistgov/oscal-cat/issues/118#issue-1605129965

**Comment by aj-stein-nist** [comment]
@JustKuzya, let's talk in the morning. I am looking at [the deployed version of the site](https://pages.nist.gov/oscal-tools/demos/cat/) and it likely has not updated yet because we push to develop, not main yet and release. Let's clear that up and close this out for the sprint tomorrow, if possible.
