### ISSUE TITLE
Validate validity of the schema for all uploaded documents

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/oscal-cat#43]
As a user I want to upload my own version of the catalog to base my catalog tailoring or profile composition. I want to make sure that the tool validates the uploaded files

- [x] Tool should validate the uploaded file for catalogs using schema
- [x] Tool should validate uploaded files for profiles using schema

**Comment by david-waltermire-nist** [comment]
Based on a conversation with @JustKuzya this was completed in a prior commit.
