### ISSUE TITLE
Confirm Circular Reference Bug Fixed

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/oscal-cat#66]
Ensure that bug previously reported and fixed in https://github.com/usnistgov/oscal-cat/commit/0245d49770aabe76dbea12d8ee1a697f475369bf is completely resolved and not present for the 0.2.0 release code.

**Comment by aj-stein-nist** [comment]
Some more intermittent state issues and it is in a `Promise`. Dmitry is working on this and will continue to debug.

**Comment by JustKuzya** [comment]
Fixed the static reference error by decoupling small session objects "Brief" from the Large Cat-Meta-Controls "Session-Data".

Now need to change Session-Service (90% Done) to the new way of persisting data and adjust interaction with the session in Author (Done), Meta (In Progress), Select Controls, Edit Controls, and Regroup Controls() pages
